modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="kyanite"
version="1.0.0"
displayName="kyanite"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.kyanite]]
    modId="neoforge"
    type="required"
    versionRange="[21.5.75,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.kyanite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.kyanite]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
    config = "kyanite.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins


# Start of user code block dependencies configuration
# End of user code block dependencies configuration